# -*- coding: utf-8 -*-
"""JPM Surefire.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QoJFvezYD6V4TC3XbzB4jbze0Nh00i4R

Mandatory packages to be imported
"""

!pip install numpy
!pip install yfinance
!pip install pandas

import numpy as np
import pandas as pd
import yfinance as yf

"""Take in VIX data (1990 till date)"""

vix_df = yf.download('^VIX')

vix_df

"""Strategy specification (1-month Moving Average)"""

